# Generated by Django 3.2.8 on 2021-10-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Person',
        ),
    ]
