# Generated by Django 3.2.8 on 2021-12-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0002_auto_20211228_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='points',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
