# Generated by Django 3.2.8 on 2021-12-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0003_status_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='points',
        ),
    ]
