# Generated by Django 3.2.8 on 2021-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0004_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=20)),
            ],
        ),
    ]
