# Generated by Django 3.2.8 on 2021-12-29 05:35

import app_crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0004_remove_activity_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='points',
            field=models.FloatField(default='1', verbose_name=app_crud.models.SumPoints),
            preserve_default=False,
        ),
    ]
