# Generated by Django 3.2.8 on 2021-12-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0007_alter_activity_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='points',
        ),
        migrations.RemoveField(
            model_name='urgency',
            name='points',
        ),
    ]
