# Generated by Django 3.2.8 on 2021-12-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0010_auto_20211231_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='points',
            field=models.FloatField(null=True),
        ),
    ]
