# Generated by Django 3.2.8 on 2022-01-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0011_alter_activity_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
