# Generated by Django 3.2.8 on 2022-01-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0012_alter_activity_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='person_points',
            field=models.IntegerField(default=0),
        ),
    ]
