# Generated by Django 3.2.8 on 2022-01-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0013_auto_20220102_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_activities',
            field=models.IntegerField(default=0),
        ),
    ]
