# Generated by Django 3.2.8 on 2022-01-04 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0017_auto_20220103_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_date_created',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date_end',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
